
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = base ;SET THIS TO "node" OR "base" TO COMPILE NODE OR BASE FIRMWARE

; BASE FIRMWARE
[env:base]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit BME280 Library @ ^2.3.0
    adafruit/Adafruit Unified Sensor @ ^1.1.15

build_src_filter =
    +<base/>
    -<node/>

; NODE FIRMWARE
[env:node]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit BME280 Library@^2.3.0

build_src_filter =
    +<node/>
    -<base/>

